### ISSUE TITLE
Import quickbuy from hypixel

### ISSUE THREAD

**Issue by ARDragssss** [ScreamingSandals/ScreamingLib#22]
its something really simple yet really effective. You can just click on a certain item and your quickbuy from hypixel gets imported.

Another great thing would be to fix the Price: 1 of iron in red glass quickbuy item and make the whole page customizable, just like the hypixel shop.

**Comment by boiscljo** [comment]
Wrong repo, quickbuy is all SBA and not screaming lib, But if ScreamingLib could make their shop work correctly even without a price that would fix the 1 of iron issue.

**Comment by ARDragssss** [comment]
i forgot to remove the quickbuy part lol but i posted the same suggestion on sba repo

**Comment by ARDragssss** [comment]
nvm i forgot to lol

**Comment by ARDragssss** [comment]
but still about the price, please fix it.

**Comment by Misat11** [comment]
Still wrong repo, but can you explain me what happens if there's no price on the glass?

**Comment by boiscljo** [comment]
Basically quickbuy works by intercepting the display function and replace the item. So to be also able to intercept the "buy" it needs a price otherwise it's a decorative item in the shop (you can't buy without a price, and fhanging the display item won't make it buyable). So quickbuy change the price and item After you you click for buying the dummy item(red glass pane) which can only be done if the dummy item has a price.

**Comment by Misat11** [comment]
Yeah, but you have two options: 1) The lore is something done by you, so you can basically end the method earlier for example. 2) For dummx items, there's another event (I think it's called (Post)ClickEvent or ActionEvent or idk, haven't used SI in ages now xdd)
